language: node_js
sudo: false

env:
  - SENECA_VER=senecajs/seneca
  - SENECA_VER=senecajs/plugin


node_js:
  - '8'
  - '10'
  - '11'

before_script:
  - npm uninstall seneca
  - npm install $SENECA_VER

after_script:
  - npm run coveralls
